version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=yacht-charter-local
    ports:
      - 5432:5432

    volumes:
      - ./postgres-data:/var/lib/postgresql/data