"""update_schema

Revision ID: 1115475d9bdd
Revises: cf17f0236910
Create Date: 2024-04-30 11:42:00.565926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1115475d9bdd'
down_revision = 'cf17f0236910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('reservations', sa.Column('yacht_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservations', 'yachts', ['yacht_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'yacht_id')
    op.drop_column('reservations', 'user_id')
    # ### end Alembic commands ###
