"""update_schema

Revision ID: b19a8a6a633d
Revises: 1115475d9bdd
Create Date: 2024-04-30 13:56:41.038499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19a8a6a633d'
down_revision = '1115475d9bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
